### ISSUE TITLE
Incorrect argument order when creating cv::Mat 

### ISSUE THREAD

**Issue by nootropicdesign** [solderspot/PiCamCVTest#1]
In main.cpp you are creating a matrix like this

```
frame = cv::Mat(cap_width, cap_height, CV_8UC4, (void*)frame_data);
```

but the argument order is wrong. Height is first, then width. I suspect you found your code only worked with square resolution, and this is why.

**Comment by solderspot** [comment]
Thanks for catching that. Yes I've only used it in square res, but then I've not never used it in anger either.
